In [1]:
import chai
import torch
import numpy as np

In [10]:
a = np.arange(6).reshape(2,3).astype(dtype=np.float16)
a,a.dtype,a.itemsize

(array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float16),
 dtype('float16'),
 2)

In [4]:
np.float16

numpy.float16

In [5]:
str(a.dtype)

'float16'

In [6]:
str(torch.float16)

'torch.float16'

In [7]:
a = torch.arange(6).reshape(2,3).to(torch.float64)
a.to(torch.float16).cpu().detach().numpy()

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float16)

In [8]:
a

tensor([[0., 1., 2.],
        [3., 4., 5.]], dtype=torch.float64)

In [2]:
import os
os.path.abspath("")

'/Users/iainmoncrief/Documents/Github/ChAI/lib'