In [18]:
import os
import sys
from pathlib import Path

import torch
import numpy as np

working_dir = Path(os.path.abspath(''))
chai_dir = (working_dir / '..' / '..').resolve()
chai_lib = chai_dir / 'lib'

sys.path.append(str(chai_lib))

import chai




In [19]:

a = torch.arange(6).reshape(2,3)
a


tensor([[0, 1, 2],
        [3, 4, 5]])

In [20]:
a.to(torch.float16).chai_save(working_dir, 'f16')
a.to(torch.float32).chai_save(working_dir, 'f32')
a.to(torch.float64).chai_save(working_dir, 'f64')

Writing json.
Writing meta.
Writing bytes.
Writing numpy.
Writing json.
Writing meta.
Writing bytes.
Writing numpy.
Writing json.
Writing meta.
Writing bytes.
Writing numpy.


In [21]:
a.isnan().bitwise_and(a.isnan())

tensor([[False, False, False],
        [False, False, False]])

In [22]:
torch.Tensor([float(1e-8)]).dtype

torch.float32

In [23]:
type(float(1e-8))

float

In [27]:
t = torch.Tensor([1.2500])
t

tensor([1.2500])

In [28]:
t[0]

tensor(1.2500)

In [29]:
t.squeeze()

tensor(1.2500)

In [30]:
t.size()

torch.Size([1])

In [33]:
t.dim()

1