In [1]:
from tinygrad import Tensor, nn


In [4]:
t = Tensor([1, 2, 3, 4])
print(t.numpy())
print(t.unsqueeze(0).numpy())

[1 2 3 4]
[[1 2 3 4]]


In [5]:
print(t.unsqueeze(1).numpy())


[[1]
 [2]
 [3]
 [4]]


In [6]:
print(t.unsqueeze(0).unsqueeze(1).numpy())

[[[1 2 3 4]]]


In [7]:
print(t.unsqueeze(0).unsqueeze(1).numpy().shape)

(1, 1, 4)


In [8]:
print(t.unsqueeze(0,1).numpy().shape)

TypeError: Tensor.unsqueeze() takes 2 positional arguments but 3 were given

In [17]:
print(t.unsqueeze(1).unsqueeze(1).squeeze(1).numpy().shape)

(4, 1)
